### PR TITLE
Fetch missing proposals

### LINKED ISSUE #1464: Trigger fetching missing proposals when majority state chooser finds a gap
Node should fetch missing proposal if it receives newer one but didn't receive older one.

Example:
1. `A` gossips proposal at height `8`, whole cluster gets the proposal.
2. `A` gossips proposal at height `10` but node `D` doesn't get proposal.
3. `A` gossips proposal at height `12`, whole cluster gets the proposal but `D` still didn't get `10`.
4. `D` should then ask original proposer for that proposal. If it doesn't work it should try asking different nodes and **pull** the missing proposal. Ideally fallback should be rather based on reputation instead of randomness.

### PR DESCRIPTION
**Pull request by tbekas**
Resolves #1464 and ~~likely~~ #1465 ~~(to be confirmed)~~

### CODE REVIEW

**Comment by marcinwadon** [comment]
Overall looks good. Please remember about using the scalafmt formatted - your code looks unformatted

File: src/main/scala/org/constellation/domain/redownload/RedownloadService.scala [hunk 1]
```diff
@@ -245,6 +263,26 @@ class RedownloadService[F[_]: NonEmptyParallel](
...
+      maybeProposals <- fetchPeerProposals(peerId)(client)
+      _ <- maybeProposals.traverse { proposals =>
+        peersProposals.modify { m =>
+          val existingProposals = m.getOrElse(peerId, Map.empty)
+          (m.updated(peerId, existingProposals ++ proposals), ())
+        }
+      }
+    } yield ()
+
+  private[redownload] def fetchPeerProposals(peerId: Id)(client: PeerClientMetadata): F[Option[SnapshotProposalsAtHeight]] =
```
[the remark this answers is not in the document]
Comment (tbekas) [reply src/main/scala/org/constellation/domain/redownload/RedownloadService.scala:278]: I started debugging argument types, so I uncurried the calls and then forgot to curry them again. Thanks for catching that.

File: src/main/scala/org/constellation/domain/redownload/RedownloadService.scala [hunk 2]
```diff
@@ -455,6 +494,33 @@ class RedownloadService[F[_]: NonEmptyParallel](
...
+      peerMajorityInfo <- peerMajorityInfo.get
+      missingProposals = missingProposalFinder.findMissingPeerProposals(majorityRange, peersProposals, peersCache)
+      _ <- missingProposals.nonEmpty.pure[F].ifM(
+        logger.info(s"No missing proposals found"),
+        logger.info(s"Found proposals missing from ${missingProposals.size} peers")
+      )
+      _ <- missingProposals.toList.traverse {
+        case (peerId, peerGaps) =>
+          val maybeSelectedPeerId = missingProposalFinder.selectPeerForFetchingMissingProposals(majorityRange, peerGaps, peerMajorityInfo - peerId)
+          maybeSelectedPeerId.traverse{ selectedPeerId => fetchProposalForPeer(peerId, selectedPeerId) }
```
[the remark this answers is not in the document]
Comment (tbekas) [reply src/main/scala/org/constellation/domain/redownload/RedownloadService.scala:509]: Fixing it.

File: src/main/scala/org/constellation/domain/redownload/RedownloadService.scala [hunk 3]
```diff
@@ -455,6 +494,33 @@ class RedownloadService[F[_]: NonEmptyParallel](
...
+      }
+    } yield ()
+  }
+
+  private def fetchProposalForPeer(peerId: Id, fromPeerId: Id): F[Unit] = {
+      for {
+        peer <- cluster.getPeerInfo.map(_.get(fromPeerId))
+        apiClient = peer.map(_.peerMetadata.toPeerClientMetadata)
+        _ <- apiClient.traverse { client =>
+          fetchAndUpdatePeerProposals(peerId)(client)
```
[the remark this answers is not in the document]
Comment (tbekas) [reply src/main/scala/org/constellation/domain/redownload/RedownloadService.scala:519]: Fixing it.

File: schema/src/main/scala/org/constellation/schema/snapshot/HeightRange.scala [hunk 4]
```diff
@@ -0,0 +1,15 @@
...
+import io.circe.{Decoder, Encoder}
+import io.circe.generic.semiauto.{deriveDecoder, deriveEncoder}
+
+/**
+  * Inclusive range of heights
+  */
+case class HeightRange(from: Long, to: Long)
+
+object HeightRange {
+  val maxRange = HeightRange(0, Long.MaxValue)
```
Comment (kpudlik) [inline schema/src/main/scala/org/constellation/schema/snapshot/HeightRange.scala:12]: Maybe `val MaxValue = HeightRange(0, Long.MaxValue)` to be consistent with naming (`Long.MaxValue`, `HeightRange.MaxValue`)

File: src/main/scala/org/constellation/domain/redownload/MissingProposalFinder.scala [hunk 5]
```diff
@@ -0,0 +1,98 @@
...
+    proposals: PeersProposals,
+    peersCache: PeersCache
+  ): Map[Id, Set[Long]] = {
+    val receivedProposals = proposals.mapValues(_.keySet)
+    val bounds = boundedRange(majorityRange)
+
+    peersCache
+      .mapValues(
+        _.map { majorityHeight =>
+          HeightRange(majorityHeight.joined.getOrElse(0L), majorityHeight.left.getOrElse(Long.MaxValue))
```
Comment (kpudlik) [inline src/main/scala/org/constellation/domain/redownload/MissingProposalFinder.scala:31]: You have already introduced `HeightRange.MaxValue` so you can reuse it here with help of `Applicative[Option]`.

```scala
Applicative[Option]
     .map2(majorityHeight.joined, majorityHeight.left)(HeightRange)
     .getOrElse(HeightRange.MaxValue)
```

or even cleaner with `cats.syntax`:

```scala
import cats.syntax._

(majorityHeight.joined, majorityHeight.left)
   .mapN(HeightRange)
   .getOrElse(HeightRange.MaxValue)
```

Thanks to that you can keep default values of `HeightRange` in one place

**Review by kpudlik — CHANGES_REQUESTED** [review]

File: schema/src/main/scala/org/constellation/schema/snapshot/HeightRange.scala (hunk 4 above)
Comment (tbekas) [reply schema/src/main/scala/org/constellation/schema/snapshot/HeightRange.scala:12]: I was thinking the same. I will change it to `MaxValue`

File: src/main/scala/org/constellation/domain/redownload/MissingProposalFinder.scala (hunk 5 above)
Comment (tbekas) [reply src/main/scala/org/constellation/domain/redownload/MissingProposalFinder.scala:31]: True, I should reuse the `MaxValue` here.

Comment (kpudlik) [reply src/main/scala/org/constellation/domain/redownload/MissingProposalFinder.scala:31]: Actually, the question is if we can have `left` without `joined` :P 

Currently, it assumes that both can be None independently :D

File: src/main/scala/org/constellation/DAO.scala [hunk 6]
```diff
@@ -398,13 +403,20 @@ class DAO(
       boundedExecutionContext
     )
 
+    missingProposalFinder = MissingProposalFinder(
+      ConfigUtil.constellation.getInt("snapshot.snapshotHeightInterval"),
+      ConfigUtil.constellation.getLong("snapshot.missingProposalOffset"),
+      ConfigUtil.constellation.getLong("snapshot.missingProposalLimit"),
+      id
+    )
```
Comment (marcinwadon) [inline src/main/scala/org/constellation/DAO.scala:411]: if there are no dependencies, I'd suggest you to create a val from it, not var and then assign

File: src/main/scala/org/constellation/domain/redownload/MissingProposalFinder.scala [hunk 7]
```diff
@@ -0,0 +1,102 @@
...
+        rangeSet(bounds.from, majorityInfo.majorityRange.from - heightInterval)
+      missingProposals -- peerGaps
+    }.toList.filter { case (_, proposalsToFill) => proposalsToFill.nonEmpty }.maximumByOption {
+      case (_, proposalsToFill) => proposalsToFill.size
+    }.map { case (id, _) => id }
+  }
+
+  def findGapRanges(majorityState: SnapshotsAtHeight): List[HeightRange] =
+    majorityState.keySet.toList.sorted
+      .sliding(2)
```
Comment (marcinwadon) [inline src/main/scala/org/constellation/domain/redownload/MissingProposalFinder.scala:68]: :+1:

File: src/main/scala/org/constellation/gossip/bisect/package.scala [hunk 8]
```diff
@@ -1,22 +1,26 @@
...
-
-    predicate(left.last)
-      .ifA(left.pure[F], right.pure[F])
-      .flatMap { partition =>
-        if (partition.size == 1) {
-          partition.headOption.filterA(predicate)
-        } else {
-          bisectA(predicate)(partition)
+  def bisectA[F[_]: Monad, A](predicate: A => F[Boolean], initSeq: Seq[A]): F[Option[A]] = {
+    def go(seq: Seq[A], acc: OptionT[F, A]): OptionT[F, A] = seq match {
```
Comment (marcinwadon) [inline src/main/scala/org/constellation/gossip/bisect/package.scala:9]: is it possible to make it tail-recursive?

File: src/main/scala/org/constellation/gossip/validation/MessageValidator.scala [hunk 9]
```diff
@@ -2,14 +2,15 @@ package org.constellation.gossip.validation
...
 import org.constellation.gossip.state.GossipMessage
 import org.constellation.schema.Id
 import org.constellation.schema.signature.HashSignature
 
 import scala.annotation.tailrec
-import scala.util.Try
+import scala.util.{Failure, Success, Try}
 
-class MessageValidator(selfId: Id) {
+class MessageValidator(selfId: Id) extends StrictLogging {
```
Comment (marcinwadon) [inline src/main/scala/org/constellation/gossip/validation/MessageValidator.scala:13]: I'd suggest avoiding using StrictLogging. Instead of that, if validation needs to make some side effects, it should be wrapped into the monad (IO)

File: src/main/scala/org/constellation/infrastructure/endpoints/SnapshotEndpoints.scala [hunk 10]
```diff
@@ -172,8 +168,8 @@ class SnapshotEndpoints[F[_]](implicit F: Concurrent[F]) extends Http4sDsl[F] {
 
   private def getLatestMajorityHeight(redownloadService: RedownloadService[F]): HttpRoutes[F] = HttpRoutes.of[F] {
     case GET -> Root / "latestMajorityHeight" =>
-      (redownloadService.lowestMajorityHeight, redownloadService.latestMajorityHeight)
-        .mapN(LatestMajorityHeight(_, _))
+      redownloadService.getMajorityRange
+        .map(range => LatestMajorityHeight(range.from, range.to))
```
Comment (marcinwadon) [inline src/main/scala/org/constellation/infrastructure/endpoints/SnapshotEndpoints.scala:172]: what do you think about:
```scala
object LatestMajorityHeight {
  def apply(range: ...): LatestMajorityHeight = new LatestMajorityHeight(range.from, range.to)
}
```

and then:
```scala
.map(LatestMajorityHeight(_))
```
?

File: src/main/scala/org/constellation/invertedmap/InvertedMap.scala [hunk 11]
```diff
@@ -22,7 +22,6 @@ final class InvertedMap[A, B] private (m: Map[B, Set[A]])
     new InvertedMap(Inverted.update(m.toMap[B1, Set[A]], key, value))
 
   override def +[B1 >: B](kv: (A, B1)): InvertedMap[A, B1] = {
-    assert(!Inverted.contains(m, kv._1), "Given key already exists!")
```
Comment (marcinwadon) [inline src/main/scala/org/constellation/invertedmap/InvertedMap.scala:25]: why? it's an important assertion and such a state is forbidden

File: src/test/scala/org/constellation/invertedmap/InvertedMapTest.scala [hunk 12]
```diff
@@ -53,10 +53,8 @@ class InvertedMapTest extends AnyFreeSpec with Matchers {
     (m + (("node4", allReady))).get("node4").isDefined shouldBe true
   }
 
-  "does not allow to set same key again" in {
-    assertThrows[AssertionError] {
-      m + (("node3", allReady))
-    }
+  "does allow to set same key again" in {
+    m + (("node3", allReady))
```
Comment (marcinwadon) [inline src/test/scala/org/constellation/invertedmap/InvertedMapTest.scala:57]: the same key cannot be set again if it exists in the inverted map. you will have a duplication then which is a forbidden state

**Review by marcinwadon — CHANGES_REQUESTED** [review]

File: src/main/scala/org/constellation/gossip/bisect/package.scala (hunk 8 above)
Comment (tbekas) [reply src/main/scala/org/constellation/gossip/bisect/package.scala:9]: Probably yes, but it might be non-trivial. There should be no risk of stack-overflow though, because it's _O(log(n))_

File: src/main/scala/org/constellation/DAO.scala (hunk 6 above)
Comment (tbekas) [reply src/main/scala/org/constellation/DAO.scala:411]: Ok, I will try

File: src/main/scala/org/constellation/gossip/bisect/package.scala (hunk 8 above)
Comment (marcinwadon) [reply src/main/scala/org/constellation/gossip/bisect/package.scala:9]: if you say so ;) I see a recursion, I think - potential stack overflow :)

File: src/test/scala/org/constellation/invertedmap/InvertedMapTest.scala (hunk 12 above)
Comment (marcinwadon) [reply src/test/scala/org/constellation/invertedmap/InvertedMapTest.scala:57]: to set the key again, you have to either remove it first and then add it again with a different value, or just use an update that does that under the hood

Comment (marcinwadon) [reply src/test/scala/org/constellation/invertedmap/InvertedMapTest.scala:57]: as an example, you cannot have an inverted map like that:
```
all ready -> node3
one offline -> node3
```
because it's ambiguous when you invert it:
```
node3 -> ???
```

Comment (marcinwadon) [reply src/test/scala/org/constellation/invertedmap/InvertedMapTest.scala:57]: hence the `key` must exist once only

File: src/main/scala/org/constellation/invertedmap/InvertedMap.scala (hunk 11 above)
Comment (tbekas) [reply src/main/scala/org/constellation/invertedmap/InvertedMap.scala:25]: Regular Maps have `+` aliased to `updated`. Current API is counterintuitive, Map can be considered as a set of key-value pairs and adding to a set should be idempotent.

File: src/main/scala/org/constellation/gossip/validation/MessageValidator.scala (hunk 9 above)
Comment (tbekas) [reply src/main/scala/org/constellation/gossip/validation/MessageValidator.scala:13]: Ok

File: src/main/scala/org/constellation/invertedmap/InvertedMap.scala (hunk 11 above)
Comment (marcinwadon) [reply src/main/scala/org/constellation/invertedmap/InvertedMap.scala:25]: as I wrote below, in this type of Map it's a forbidden state. it has been created purely for optimization and your current change breaks the important assumption about an Inverted Map.

File: src/main/scala/org/constellation/infrastructure/endpoints/SnapshotEndpoints.scala (hunk 10 above)
Comment (tbekas) [reply src/main/scala/org/constellation/infrastructure/endpoints/SnapshotEndpoints.scala:172]: Fine with me, I will change it.

**Review by marcinwadon — CHANGES_REQUESTED** [review]
Previous msgs

File: src/test/scala/org/constellation/invertedmap/InvertedMapTest.scala (hunk 12 above)
Comment (tbekas) [reply src/test/scala/org/constellation/invertedmap/InvertedMapTest.scala:57]: You're probably right about this. I will look at it tomorrow.

File: src/main/scala/org/constellation/invertedmap/InvertedMap.scala (hunk 11 above)
Comment (tbekas) [reply src/main/scala/org/constellation/invertedmap/InvertedMap.scala:25]: I'm marking this one as resolved to continue discussion in a single thread ([link](https://github.com/Constellation-Labs/constellation/pull/1474#discussion_r564935519)).

File: src/test/scala/org/constellation/invertedmap/InvertedMapTest.scala (hunk 12 above)
Comment (tbekas) [reply src/test/scala/org/constellation/invertedmap/InvertedMapTest.scala:57]: Ok, so two things:
1. In you're example the `InvertedMap` can't have repeating values, which is not the case for this implementation. The `InvertedMap[A, B]` doesn't have to be injective (różnowartościowa), because the underlying map is of type `Map[B, Set[A]]` which solves the issue.
2. This plus method is just an alias to the `updated` method, which first removes the existing association and then adds a new one, so the underlying data is kept consistent.

You may wonder why I'm aliasing this function at all and why can't I just change the invocations of `+` to `updated`. So the reason is that  we're not calling it directly in our code, but rather indirectly by calling the `MapLike`'s `++` (add all) method, which in turn calls `+` (add) method.

Comment (kpudlik) [reply src/test/scala/org/constellation/invertedmap/InvertedMapTest.scala:57]: I agree with Marcin. `Set` does not solve the problem. `Map[B, Set[A]]` only makes `B` unique and `A` unique *wthin the single set* but we want `A` to be unique globally in the whole map:

```
all ready -> Set(node3, ...)
one offline -> Set(node3, ...)
```

Such state is incorrect because it says that "node3 has all the nodes ready" and "node3 has one node offline".

**Review by marcinwadon — APPROVED** [review]

**Review by kpudlik — APPROVED** [review]
