### PR TITLE
[#1073] Fix updating peers proposals by making them immutable

### LINKED ISSUE #1073: Merge proposals instead of overwriting
image

If we block communication between nodes for a while (so proposal requests are timing out) then it gets no proposals from others which makes fallback to empty Map. Because all nodes timed out and "returned" empty Map it sets `0` as majority for a moment. It is incorrect situation as we should never overwrite proposal  at height. Once set proposal should never change for specific height.

So basically modify `RedownloadService.updatePeerProposal` to set only these heights in `RedownloadService.peersProposals` which haven't been set yet. `peerProposals` should be immutable for specific heights no matter what.

### PR DESCRIPTION
**Pull request by TheMMaciek**
In the situation of a timeout on a request fetching proposals, the proposals Map fallback's to an empty Map. Because we were just overriding the proposals in the situation of no communication between nodes we could get majority equal to 0. By making proposals immutable this situation will not happen and also the history of proposals can not be changed. Only new information can be added.

Resolves #1073

### CODE REVIEW

File: src/test/scala/org/constellation/domain/redownload/RedownloadServiceTest.scala [hunk 1]
```diff
@@ -323,6 +325,87 @@ class RedownloadServiceTest
...
+    val peer1Proposals = Map(1L -> SnapshotProposal("hash2p1", SortedMap.empty), 2L -> SnapshotProposal("hash3p1", SortedMap.empty))
+    val peer2Proposals = Map(1L -> SnapshotProposal("hash1p2", SortedMap.empty), 2L -> SnapshotProposal("hash2p2", SortedMap.empty))
+
+    "for empty proposals Map" - {
+      /**
+        * TODO: Consider as a feature.
+        * If proposals are immutable, it can be a sanity check that nodes are not changing the proposals.
+        */
+      "should not override previously stored proposals" in {
+        // preparing mocks and initial state
```
Comment (marcinwadon) [inline src/test/scala/org/constellation/domain/redownload/RedownloadServiceTest.scala:348]: You don't need to repeat it every test :)

File: src/test/scala/org/constellation/domain/redownload/RedownloadServiceTest.scala [hunk 2]
```diff
@@ -323,6 +325,87 @@ class RedownloadServiceTest
...
+    )
+    val initialPeersProposals = Map(peer1 -> Map(1L -> SnapshotProposal("hash1p1", SortedMap.empty)))
+    val peer1Proposals = Map(1L -> SnapshotProposal("hash2p1", SortedMap.empty), 2L -> SnapshotProposal("hash3p1", SortedMap.empty))
+    val peer2Proposals = Map(1L -> SnapshotProposal("hash1p2", SortedMap.empty), 2L -> SnapshotProposal("hash2p2", SortedMap.empty))
+
+    "for empty proposals Map" - {
+      /**
+        * TODO: Consider as a feature.
+        * If proposals are immutable, it can be a sanity check that nodes are not changing the proposals.
+        */
```
Comment (marcinwadon) [inline src/test/scala/org/constellation/domain/redownload/RedownloadServiceTest.scala:346]: this comment is no longer needed

File: src/main/scala/org/constellation/domain/redownload/RedownloadService.scala [hunk 3]
```diff
@@ -143,8 +143,16 @@ class RedownloadService[F[_]: NonEmptyParallel](
       responses <- apiClients.traverse { client =>
         fetchCreatedSnapshots(client).map(client.id -> _)
       }
+      newProposals = responses.toMap
       proposals <- peersProposals.modify { m =>
-        val updated = m ++ responses.toMap
+        val updated = m.map { case (id, proposalsAtHeight) =>
+          val diff = newProposals
+            .getOrElse(id, Map.empty)
+            .filterKeys(height => !proposalsAtHeight.keySet.contains(height))
```
Comment (kpudlik) [inline src/main/scala/org/constellation/domain/redownload/RedownloadService.scala:151]: Alternatively a hipster way of diffing Maps:

```
val diff = newProposals.getOrElse(id, Map.empty) -- proposalsAtHeight.keySet
```

As it looks imo cleaner when you use `++` with `--` instead of `++` with `filterKeys`

File: src/main/scala/org/constellation/domain/redownload/RedownloadService.scala [hunk 4]
```diff
@@ -143,8 +143,16 @@ class RedownloadService[F[_]: NonEmptyParallel](
...
+
+          id -> (proposalsAtHeight ++ diff)
+        } ++ newProposals.filterKeys(id => !m.keySet.contains(id))
```
Comment (kpudlik) [inline src/main/scala/org/constellation/domain/redownload/RedownloadService.scala:154]: Same here, alernatively just `} ++ (newProposals -- m.keySet)`
