### PR TITLE
Fix validation for many overflowing transactions

### LINKED ISSUE #994: Improper balance validation in transaction verification
Add filter step to filter in validateSourceAddress, filter for sum of total balance in all tx for an address > max supply

### PR DESCRIPTION
**Pull request by marcinwadon**
Resolves #994

### CODE REVIEW

File: src/main/scala/org/constellation/checkpoint/CheckpointBlockValidator.scala [hunk 1]
```diff
@@ -185,14 +185,14 @@ class CheckpointBlockValidator[F[_]: Sync](
 
     def validateBalance(address: String, t: Iterable[Transaction]): F[ValidationResult[List[Transaction]]] =
       lookup(address).map { balance =>
-        val amount = t.map(_.amount).sum
+        val amount = t.map(_.amount).map(BigInt(_)).sum
```
Comment (kpudlik) [inline src/main/scala/org/constellation/checkpoint/CheckpointBlockValidator.scala:188]: I am wondering if we should always use BigInt (which is no that efficient) instead of using it only if it overflows 🤔 

But maybe it is microoptimisation which we do not need
