### PR TITLE
Data migration fix and channel storage disabled

### LINKED ISSUE #1223: Data migration failures

### LINKED ISSUE #1224: Get rid of H2 database
Node operator reported a problem with starting an app. We've figured out that it takes ages to create a database noone is using:

```
private val db = Database.forConfig("h2mem1")
  db.run(setup).get()
  logger.info("Created!")
```

### PR DESCRIPTION
**Pull request by marcinwadon**
Resolves #1223 
Resolves #1224

### CODE REVIEW

File: src/main/scala/org/constellation/storage/SnapshotService.scala [hunk 1]
```diff
@@ -82,17 +83,32 @@ class SnapshotService[F[_]: Concurrent](
...
+        .leftMap(SnapshotUnexpectedError(_).asInstanceOf[SnapshotError])
       _ <- validateBlocksWithinHeightInterval(blocksWithinHeightInterval)
       allBlocks = blocksWithinHeightInterval.map(_.get).sortBy(_.checkpointBlock.baseHash)
 
       hashesForNextSnapshot = allBlocks.map(_.checkpointBlock.baseHash)
-      publicReputation <- EitherT.liftF(trustManager.getPredictedReputation)
-      nextSnapshot <- EitherT.liftF(getNextSnapshot(hashesForNextSnapshot, publicReputation))
+      publicReputation <- trustManager.getPredictedReputation.attemptT.leftMap(SnapshotUnexpectedError)
+      nextSnapshot <- getNextSnapshot(hashesForNextSnapshot, publicReputation).attemptT.leftMap(
+        SnapshotUnexpectedError(_).asInstanceOf[SnapshotError]
```
Comment (kpudlik) [inline src/main/scala/org/constellation/storage/SnapshotService.scala:106]: You rather need `.leftWiden[SnapshotError]` to "fix" type variance

File: src/main/scala/org/constellation/storage/SnapshotService.scala [hunk 2]
```diff
@@ -82,17 +83,32 @@ class SnapshotService[F[_]: Concurrent](
...
+      )
+      _ <- nextSnapshotHash
+        .modify(_ => (nextSnapshot.hash, ()))
+        .attemptT
+        .leftMap(SnapshotUnexpectedError(_).asInstanceOf[SnapshotError])
```
Comment (kpudlik) [inline src/main/scala/org/constellation/storage/SnapshotService.scala:111]: You rather need `.leftWiden[SnapshotError]` to "fix" type variance

File: src/main/scala/org/constellation/storage/SnapshotService.scala [hunk 3]
```diff
@@ -106,20 +122,27 @@ class SnapshotService[F[_]: Concurrent](
...
       )
       _ <- applySnapshot()
-      _ <- EitherT.liftF(lastSnapshotHeight.set(nextHeightInterval.toInt))
-      _ <- EitherT.liftF(acceptedCBSinceSnapshot.update(_.filterNot(hashesForNextSnapshot.contains)))
-      _ <- EitherT.liftF(calculateAcceptedTransactionsSinceSnapshot())
-      _ <- EitherT.liftF(updateMetricsAfterSnapshot())
+      _ <- lastSnapshotHeight
+        .set(nextHeightInterval.toInt)
+        .attemptT
+        .leftMap(SnapshotUnexpectedError(_).asInstanceOf[SnapshotError])
```
Comment (kpudlik) [inline src/main/scala/org/constellation/storage/SnapshotService.scala:128]: You rather need `.leftWiden[SnapshotError]` to "fix" type variance

File: src/main/scala/org/constellation/storage/SnapshotService.scala [hunk 4]
```diff
@@ -106,20 +122,27 @@ class SnapshotService[F[_]: Concurrent](
...
+      _ <- acceptedCBSinceSnapshot
+        .update(_.filterNot(hashesForNextSnapshot.contains))
+        .attemptT
+        .leftMap(SnapshotUnexpectedError(_).asInstanceOf[SnapshotError])
```
Comment (kpudlik) [inline src/main/scala/org/constellation/storage/SnapshotService.scala:132]: You rather need `.leftWiden[SnapshotError]` to "fix" type variance

File: src/main/scala/org/constellation/storage/SnapshotService.scala [hunk 5]
```diff
@@ -106,20 +122,27 @@ class SnapshotService[F[_]: Concurrent](
...
+      _ <- calculateAcceptedTransactionsSinceSnapshot().attemptT
+        .leftMap(SnapshotUnexpectedError(_).asInstanceOf[SnapshotError])
```
Comment (kpudlik) [inline src/main/scala/org/constellation/storage/SnapshotService.scala:134]: You rather need `.leftWiden[SnapshotError]` to "fix" type variance

File: src/main/scala/org/constellation/storage/SnapshotService.scala [hunk 6]
```diff
@@ -106,20 +122,27 @@ class SnapshotService[F[_]: Concurrent](
...
+      _ <- updateMetricsAfterSnapshot().attemptT.leftMap(SnapshotUnexpectedError(_).asInstanceOf[SnapshotError])
```
Comment (kpudlik) [inline src/main/scala/org/constellation/storage/SnapshotService.scala:135]: You rather need `.leftWiden[SnapshotError]` to "fix" type variance

File: src/main/scala/org/constellation/storage/SnapshotService.scala [hunk 7]
```diff
@@ -106,20 +122,27 @@ class SnapshotService[F[_]: Concurrent](
...
 
       snapshot = StoredSnapshot(nextSnapshot, allBlocks)
-      _ <- EitherT.liftF(storedSnapshot.set(snapshot))
+      _ <- storedSnapshot.set(snapshot).attemptT.leftMap(SnapshotUnexpectedError(_).asInstanceOf[SnapshotError])
```
Comment (kpudlik) [inline src/main/scala/org/constellation/storage/SnapshotService.scala:138]: You rather need `.leftWiden[SnapshotError]` to "fix" type variance

File: src/main/scala/org/constellation/storage/SnapshotService.scala [hunk 8]
```diff
@@ -106,20 +122,27 @@ class SnapshotService[F[_]: Concurrent](
...
       // TODO: pass stored snapshot to writeSnapshotToDisk
       _ <- writeSnapshotToDisk(snapshot.snapshot)
       _ <- writeSnapshotInfoToDisk()
       // For now we do not restore EigenTrust model
       //      _ <- writeEigenTrustToDisk(snapshot.snapshot)
 
-      _ <- EitherT.liftF(markLeavingPeersAsOffline())
+      _ <- markLeavingPeersAsOffline().attemptT.leftMap(SnapshotUnexpectedError(_).asInstanceOf[SnapshotError])
```
Comment (kpudlik) [inline src/main/scala/org/constellation/storage/SnapshotService.scala:145]: You rather need `.leftWiden[SnapshotError]` to "fix" type variance

File: src/main/scala/org/constellation/storage/SnapshotService.scala [hunk 9]
```diff
@@ -82,17 +83,32 @@ class SnapshotService[F[_]: Concurrent](
...
-      nextHeightInterval <- EitherT.liftF(getNextHeightInterval)
-      minActiveTipHeight <- EitherT.liftF(LiftIO[F].liftIO(dao.getActiveMinHeight))
-      minTipHeight <- EitherT.liftF(concurrentTipService.getMinTipHeight(minActiveTipHeight))
+      nextHeightInterval <- getNextHeightInterval.attemptT.leftMap(
+        SnapshotUnexpectedError(_).asInstanceOf[SnapshotError]
+      )
+      minActiveTipHeight <- LiftIO[F]
+        .liftIO(dao.getActiveMinHeight)
+        .attemptT
+        .leftMap(SnapshotUnexpectedError(_).asInstanceOf[SnapshotError])
```
Comment (kpudlik) [inline src/main/scala/org/constellation/storage/SnapshotService.scala:92]: You rather need `.leftWiden[SnapshotError]` to "fix" type variance

File: src/main/scala/org/constellation/storage/SnapshotService.scala [hunk 10]
```diff
@@ -82,17 +83,32 @@ class SnapshotService[F[_]: Concurrent](
...
+      minTipHeight <- concurrentTipService
+        .getMinTipHeight(minActiveTipHeight)
+        .attemptT
+        .leftMap(SnapshotUnexpectedError(_).asInstanceOf[SnapshotError])
```
Comment (kpudlik) [inline src/main/scala/org/constellation/storage/SnapshotService.scala:96]: You rather need `.leftWiden[SnapshotError]` to "fix" type variance
