### PR TITLE
Fix for downloading last majority snapshot

### LINKED ISSUE #1417: Fix Downloading only last majority snapshot
Previous implementation that was a part of #1184 is causing nodes failing to join.

```
2020-11-03 18:24:55,287 [unbounded-pool-1-thread-5] [] ERROR o.c.d.r.DownloadService - Error during download process 
java.nio.file.NoSuchFileException: /root/constellation/tmp/42d3fe0a42/snapshots/efbe4e44739fb788dc4260704c3be286e09078dc728025f721994ba930cab53e
```

### PR DESCRIPTION
**Pull request by tbekas**
Resolves #1417

### CODE REVIEW

**Review by kpudlik — DISMISSED** [review]

File: src/main/scala/org/constellation/domain/redownload/RedownloadService.scala [hunk 1]
```diff
@@ -380,8 +373,9 @@ class RedownloadService[F[_]: NonEmptyParallel](
 
       maxMajorityHeight = maxHeight(majorityState)
       ignorePoint = getIgnorePoint(maxMajorityHeight)
+      majorityStateCutoff = if (isDownload) maxMajorityHeight else ownPeer.getOrElse(maxMajorityHeight)
       meaningfulAcceptedSnapshots = takeHighestUntilKey(acceptedSnapshots, ignorePoint)
-      meaningfulMajorityState = takeHighestUntilKey(majorityState, ignorePoint)
+      meaningfulMajorityState = majorityState.filterKeys(_ >= majorityStateCutoff)
```
Comment (marcinwadon) [inline src/main/scala/org/constellation/domain/redownload/RedownloadService.scala:378]: why you removed `takeHighestUntilKey`?

**Review by marcinwadon — CHANGES_REQUESTED** [review]
Changelog missing

File: src/main/scala/org/constellation/domain/redownload/RedownloadService.scala (hunk 1 above)
Comment (kpudlik) [reply src/main/scala/org/constellation/domain/redownload/RedownloadService.scala:378]: Probably because it uses `>` instead of `>=`

Comment (tbekas) [reply src/main/scala/org/constellation/domain/redownload/RedownloadService.scala:378]: takeHighest would result in `filterKeys(_ > majorityStateCutoff)` (greater than, instead of greater than equal)

Comment (marcinwadon) [reply src/main/scala/org/constellation/domain/redownload/RedownloadService.scala:378]: but it does not take into account the ignore point, which has been used before, does it?

Comment (tbekas) [reply src/main/scala/org/constellation/domain/redownload/RedownloadService.scala:378]: No, it doesn't. The ignore point is just `maxMajorityHeight - 40`.

Comment (marcinwadon) [reply src/main/scala/org/constellation/domain/redownload/RedownloadService.scala:378]: So it's wrong IMO. It should ignore everything below joining height but from the `takeHighestUntilKey(majorityState, ignorePoint)`, so `takeHighestUntilKey(majorityState, ignorePoint).filterKeys(_ >= majorityStateCutoff)` not from `majorityState` directly

Comment (marcinwadon) [reply src/main/scala/org/constellation/domain/redownload/RedownloadService.scala:378]: So it should ignore everything below both ignorePoint and majorityStateCutoff, whatever is higher

Comment (tbekas) [reply src/main/scala/org/constellation/domain/redownload/RedownloadService.scala:378]: @marcinwadon Do you think that should I remove the `ignorePoint`? The `ignorePoint` is used to trim down the `meaningfulAcceptedSnapshots`.

Comment (marcinwadon) [reply src/main/scala/org/constellation/domain/redownload/RedownloadService.scala:378]: Why remove? I don't understand

Comment (tbekas) [reply src/main/scala/org/constellation/domain/redownload/RedownloadService.scala:378]: `takeHighestUntilKey(majorityState, ignorePoint).filterKeys(_ >= majorityStateCutoff)` that will be no different than current implementation.

Comment (marcinwadon) [reply src/main/scala/org/constellation/domain/redownload/RedownloadService.scala:378]: tl;dr; there is a case that joining height can be lower than the ignore point and then the ignore point should be taken into account

Comment (tbekas) [reply src/main/scala/org/constellation/domain/redownload/RedownloadService.scala:378]: Resolved. @marcinwadon was right, the `ignorePoint` filter has to stay.

Comment (kpudlik) [reply src/main/scala/org/constellation/domain/redownload/RedownloadService.scala:378]: `majorityStateCutoff` is I guess always above `ignorePoint` so

`majorityState.filterKeys(_ >= majorityStateCutoff)` and `takeHighestUntilKey(majorityState, ignorePoint).filterKeys(_ >= majorityStateCutoff)` produce the same @marcinwadon

Comment (marcinwadon) [reply src/main/scala/org/constellation/domain/redownload/RedownloadService.scala:378]: @kpudlik no. 

let's say max majorityState is 100
own joining height is 40

`majorityState.filterKeys(_ >= majorityStateCutoff)` will return `40+`
but it should produce `60+` (100 - majority state inverval (40))

Comment (kpudlik) [reply src/main/scala/org/constellation/domain/redownload/RedownloadService.scala:378]: Ah right, I see that it is applied to both redownload and download. Then it is wrong implementation.

**Review by marcinwadon — CHANGES_REQUESTED** [review]
Missing build.sbt version change

**Review by marcinwadon — APPROVED** [review]
