### PR TITLE
Pending transactions that no longer can be accepted are removed

### LINKED ISSUE #1257: Remove transactions stuck in pendingTrasactionsMemPool
Currently if transaction is incorrect e.g. it has correct ordinal but incorrect prevHash (it doesn't form a chain with other transactions) then it will get stuck in pending memPool. We should implement some logic that can clean transactions stuck in pending. We could implement lru cache with some timeout and also remove transactions while accepting checkpoint blocks - e.i. if transaction with certain ordinal is being accepted during checkpoint block acceptance than transactions with that or lower ordinal can be removed from pending.

Could you add more detail @buckysballs 

connected to #1216

### PR DESCRIPTION
**Pull request by tbekas**
Resolves #1257

### CODE REVIEW

File: src/test/scala/org/constellation/domain/transaction/TransactionServiceTest.scala [hunk 1]
```diff
@@ -398,7 +398,43 @@ class TransactionServiceTest
       txService.put(tx, ConsensusStatus.Unknown).unsafeRunSync
 
       val txs = txService.findByPredicate(_ => true).unsafeRunSync
-      txs isEmpty
+      txs shouldBe empty
```
Comment (tbekas) [inline src/test/scala/org/constellation/domain/transaction/TransactionServiceTest.scala:401]: That line is not related to the main issue, but I just noticed that I left this error some time ago (`isEmpty` is not an assertion).

If you want I can move it to a different PR, please let me know.

**Review by marcinwadon — APPROVED** [review]
